### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by rgarrigue** [de-vri-es/setup-git-credentials#3]
Hi there

I'm using https://github.com/nektos/act for local crafting / debuguing of my GitHub Actions. 

It's :boom: 'ing like this

```
[Tests/tests] ⭐  Run Setup git credentials
[Tests/tests]   ☁  git clone 'https://github.com/fusion-engineering/setup-git-credentials' # ref=v2
[Tests/tests]   🐳  docker cp src=/home/remy/.cache/act/fusion-engineering-setup-git-credentials@v2 dst=/actions/
| internal/modules/cjs/loader.js:985
|   throw err;
|   ^
| 
| Error: Cannot find module '@actions/core'
| Require stack:
| - /actions/fusion-engineering-setup-git-credentials@v2/lib/main.js
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
|     at Module.require (internal/modules/cjs/loader.js:1044:19)
|     at require (internal/modules/cjs/helpers.js:77:18)
|     at Object.<anonymous> (/actions/fusion-engineering-setup-git-credentials@v2/lib/main.js:18:27)
|     at Module._compile (internal/modules/cjs/loader.js:1158:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
|     at Module.load (internal/modules/cjs/loader.js:1002:32)
|     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
|     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: [
|     '/actions/fusion-engineering-setup-git-credentials@v2/lib/main.js'
|   ]
| }
```

Can you give me an hint about what went wrong ? 

If you want to reproduce, I'm using act 0.2.8 (~ latest) with the command `act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 -s GIT_CREDENTIALS=https://me:mytoken@github.com
` (warning, this docker image is ~18G big) and here's my workflow

```
name: Tests

on:
  push:
    tags:
      - "*"

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@master
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install Tox
        run: pip install tox

      - name: Cache Tox
        uses: actions/cache@master
        with:
          path: ~/.tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Install Tox
        run: pip install tox

      - name: Setup git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Run Tox
        run: tox
```
