### ISSUE TITLE
Credentials are not properly configured and/or propogated

### ISSUE THREAD

**Issue by shivarammysore** [de-vri-es/setup-git-credentials#7]
I have an Organization setting for my repos.  I am building go binary for one with another private module in a different repo.  The token supplied has organization setting.

With the below action the repo itself is not found.  Am I missing any settings?

```yaml
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{ secrets.SNMIX_REPO_ACCESS_TOKEN }}
    - run: cat ~/.gitconfig

```

Output when running the action:

```console
Run fusion-engineering/setup-git-credentials@v2
  with:
    credentials: ***
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.5/x64
git config --global credential.helper store
git config --global url.https://github.com/.insteadOf ssh://git@github.com/
git config --global --add url.https://github.com/.insteadOf git@github.com:

Run cat ~/.gitconfig
[credential]
	helper = store
[url "https://github.com/"]
	insteadOf = ssh://git@github.com/
	insteadOf = git@github.com:
```

**Comment by de-vri-es** [comment]
I'm guessing that your secret is just the github token. It should instead be git credentials in the format specified by `man 7 git-credential-store` (under `STORAGE FORMAT`).  

You can change the credentials settings to this (you'll have to fill-in the `$username` bit):
```yaml
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: https://$username:${{ secrets.SNMIX_REPO_ACCESS_TOKEN }}@github.com/
    - run: cat ~/.gitconfig
```

Alternatively, you can put that directly in a secret, which also allows you to add credentials for different URLs.

Does this solve your issue? :)

**Comment by shivarammysore** [comment]
Thanks for the response.  I did not understand your "alternate" suggestion.  Can you give an example?

I tried your suggestion: ($username replaced with correct one)

```yaml
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: https://$username:${{ secrets.SNMIX_REPO_ACCESS_TOKEN }}@github.com/
    - run: cat ~/.gitconfig
```

output:
```console
Run fusion-engineering/setup-git-credentials@v2
  with:
    credentials: ***github.com/
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.5/x64
git config --global credential.helper store
git config --global url.https://github.com/.insteadOf ssh://git@github.com/
git config --global --add url.https://github.com/.insteadOf git@github.com:

Run cat ~/.gitconfig
[credential]
	helper = store
[url "https://github.com/"]
	insteadOf = ssh://git@github.com/
	insteadOf = git@github.com:

....
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Determining the default branch
  Retrieving the default branch name
  Not Found
```

**Comment by de-vri-es** [comment]
> ```
> Setting up auth
>   /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
>   /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
>   /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
>   /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
>   /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
> ```

Where does this come from? It doesn't look like anything that `git-setup-credentials` does. It may conflict with `git-setup-credentials`.

**Comment by shivarammysore** [comment]
Hello,

I have `myorg/repo-a` in which this github action runs.   Both `repo-a` and `repo-b` are Go lang programs.  The corresponding workflow yaml is as below:

```yaml
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: https://$username:${{ secrets.MY_PAT }}@github.com/
    - run: cat ~/.gitconfig

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      env:
          GOPRIVATE: "github.com/myorg/*"
      with:
        fetch-depth: 1
        path: src/github.com/myorg/repo-a
        submodules: true

    - name: Checkout myorg/repo-b
      uses: actions/checkout@v2
      with:
        repository: switchnomix/repo-b
        path: src/github.com/myorg/repo-b
```

The first checkout of `repo-a` works.  The second checkout of `repo-b` fails.  The details of the failure were posted previously.
Does this help?

**Comment by nWacky** [comment]
I might've had a similar problem

I tried cloning a local repository. In CI repository was not found, but locally everything worked.

By default Github Actions (and Azure CI) adds an extra header to clone the repository

Git config file examples from ci workflows after running
`actions/checkout` and `de-vri-es/setup-git-credentials`:

```
# Run cat .git/config
> cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/octocat/Hello-World
	fetch = +refs/heads/*:refs/remotes/origin/*
[gc]
	auto = 0
[http "https://github.com/"]
	extraheader = AUTHORIZATION: basic ***
[branch "main"]
	remote = origin
	merge = refs/heads/main

# Run cat ~/.gitconfig
> cat ~/.gitconfig
[credential]
	helper = store
[url "https://github.com/"]
	insteadOf = ssh://git@github.com/
	insteadOf = git@github.com:
```

Running `git config --local --unset  http.https://github.com/.extraheader` to remove the extra header fixed the issue for me

CI workflow example:

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: remove default credentials
    run: git config --local --unset  http.https://github.com/.extraheader

  - uses: de-vri-es/setup-git-credentials@v2
    with:
      credentials: ${{secrets.GIT_CREDENTIALS}}
```

**Comment by de-vri-es** [comment]
Hmm, that seems odd. The `extraheader` is configured in `.git/config`, not the global git configuration. Why would it be used? :o 

What command/tool is cloning the extra repositories?

**Comment by nWacky** [comment]
I was trying to install a node module from a private git repository.

<details>

<summary> The ci looked like this </summary>

```yaml
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --no-audit
```

</details>

I think `actions/checkout@v4` set the `extraheader` to clone the local repository

Then `npm ci` tried to check that a private repository on github exists with

```bash
git --no-replace-objects ls-remote ssh://git@github.com/octocat/private.git
```

I think git used both `extraheader` from local config and global credentials, and that didn't work
